baseline:
  noise_var: 1e-2

# GP Linear Kernel
gp_exact_reg_lin:
  noise_var: 1e-2
  signal_var: 1.0
  kernel:
    id: linear
gp_exact_reg_lin_ard:
  noise_var: 1e-2
  signal_var: 1.0
  kernel:
    id: linear
    ard_num_dims: auto

# GP RBF Kernel
gp_exact_reg_rbf:
  noise_var: 1e-2
  signal_var: 1.0
  kernel:
    id: rbf
    lengthscale: auto
gp_exact_reg_rbf_ard:
  noise_var: 1e-2
  signal_var: 1.0
  kernel:
    id: rbf
    lengthscale: auto
    ard_num_dims: auto

# GP Matern 5/2 Kernel
gp_exact_reg_matern52:
  noise_var: 1e-2
  signal_var: 1.0
  kernel: 
    id: matern
    nu: 2.5
    lengthscale: auto
gp_exact_reg_matern52_ard:
  noise_var: 1e-2
  signal_var: 1.0
  kernel: 
    id: matern
    nu: 2.5
    lengthscale: auto
    ard_num_dims: auto

# GP Approx RBF Kernel
gp_approx_reg_rbf:
  num_ip: 100
  noise_var: 1e-2
  signal_var: 1.0
  kernel:
    id: rbf
    lengthscale: auto
gp_approx_reg_rbf_ard:
  num_ip: 100
  noise_var: 1e-2
  signal_var: 1.0
  kernel:
    id: rbf
    lengthscale: auto
    ard_num_dims: auto

# GP Approx Matern 5/2 Kernel
gp_approx_reg_matern52:
  num_ip: 100
  noise_var: 1e-2
  signal_var: 1.0
  kernel:
    id: matern
    nu: 2.5
    lengthscale: auto
gp_approx_reg_matern52_ard:
  num_ip: 100
  noise_var: 1e-2
  signal_var: 1.0
  kernel:
    id: matern
    nu: 2.5
    lengthscale: auto
    ard_num_dims: auto

# Laplace Approximation
la_reg_nonlinear:
  layers: [128]
  activation: tanh
  noise_var: 1e-2
  subset_of_weights: last_layer
  hessian_structure: diag
  pred_type: glm

# Features Deep Ensemble
ensemble_reg_linear:
  num_models: 10
  # features: layer_norm
ensemble_reg_nonlinear:
  num_models: 10
  layers: [128]
  activation: tanh
  # features: layer_norm

# Convnext Deep Ensemble
ensemble_timm_reg_convnext_atto:
  features_model: "convnextv2_atto.fcmae_ft_in1k"
  num_models: 5
  layers: [128]
  activation: tanh
ensemble_timm_reg_convnext_base:
  features_model: "convnext_base.fb_in1k"
  num_models: 5
  layers: [128]
  activation: tanh

# Dino Deep Ensemble
ensemble_timm_reg_dinov2_small:
  features_model: "vit_small_patch14_reg4_dinov2.lvd142m"
  num_models: 5
  layers: [128]
  activation: tanh
ensemble_timm_reg_dinov2_base:
  features_model: "vit_base_patch14_reg4_dinov2.lvd142m"
  num_models: 5
  layers: [128]
  activation: tanh
