train:
  epochs: 500
  tol: 1.0e-5
  patience: 100
  verbose: false

optimizer:
  lr: 1.0e-2
  weight_decay: 0.0

scheduler:
  mode: min
  factor: 0.8
  patience: 200
  threshold: 1.0e-4
  threshold_mode: rel
  cooldown: 0
  min_lr: 0
  eps: 1.0e-8

dataloader:
  batch_size: 20000 # 2056
  shuffle: true
  # num_workers: 12
  # pin_memory: true
  # prefetch_factor: 4
  # persistent_workers: true
  # multiprocessing_context: spawn

gpytorch:
  max_cholesky_size: 800
  cg_tolerance: 1
  max_cg_iterations: 1000
  fast_computations:
    covar_root_decomposition: true
    log_prob: true
    solves: true
